apiVersion: v1
kind: Service
metadata:
  name: {{ include "voice-data-backend.fullname" . }}
  labels:
    {{- include "voice-data-backend.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "voice-data-backend.selectorLabels" . | nindent 4 }}
