{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "voice-data-backend.fullname" . }}
  labels:
    {{- include "voice-data-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "voice-data-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.prometheus.path }}
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: {{ include "voice-data-backend.name" . }}
          action: keep
{{- end }}
{{- end }}
